main: main.java.worldmc.WMC
name: WorldMC-Main
version: '2.3'
description: Does all the things
author: Uriyang
website: https://www.worldmc.net/home
api-version: 1.16
load: POSTWORLD
commands:
  wmcreload:
   description: Reload the configuration
   permission: wmc.reload
   permission-message: No permission
   usage: /<command>
  wmcgivespawner:
   description: Give a spawner
   permission: wmc.givespawner
   permission-message: No permission
   usage: /<command> (player) (type) [<amount>]
