#=====================#
#   WMC-Main-Config   #
#      by Uriang      #
#=====================#
# Discord:Khasar#2151 #
#=====================#

# Feature list:
#   Random-Spawn
#   No-Gold-Drops
#   Remove mobs pathfinding and targetting based on criteria
#   Recipe tweaking
#   Silk touch spawners
#   Welcome rewards
#   Combat tag
#   Player protection

# {USERNAME} for username in commands

# All spawn reasons: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
# All mobs can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
# All tools / Materials can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# All sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# All damage causes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html

#=====================#
#   WMC-Random-Spawn  #
#=====================#

# Random teleport on death and first join
# Will not teleport if bed spawn 
# Or town spawn is set if towny is installed

random-spawn:
    # Main enable for random spawning
    enabled: true

    # Pre-setup for a 1:500 map
    minX: -35000
    maxX: 35000
    minZ: -17000
    maxZ: 17000
    
    # World which it is to spawn the player in
    # !Requires server restart to change!
    world-name: 'world'
    
    teleport-mode: 'ground_tp'
    
    # 
    # Teleport-Mode can be 'height_limit_tp' or 'ground_tp'
    #
    # Explanations:
    # 'ground_tp':
    #      Can only be used if the area selected is pre-generated
    #      Otherwise it will throw exceptions
    #
    # 'height_limit_tp':
    #      Will apply resistance 100 for 300 ticks to prevent fall damage
    #      Works if the terrain is not pre-generated
    #      Didn't really need to be implemented but incase you'd want to use it on
    #      maps that arent pre-generated
    #
    
    # Safe spawn materials
    safe-materials:
        - 'GRASS'
        - 'DIRT'
        - 'GRASS_BLOCK'
        - 'RED_SAND'
        - 'SAND'
        - 'CLAY'
        - 'TERRACOTTA'
        - 'RED_TERRACOTTA'
        - 'ORANGE_TERRACOTTA'
        - 'COBBLESTONE'
        - 'COARSE_DIRT'
        - 'PODZOL'
    
    # How many times should it try to find a suited location before failing?
    try-attempts: 100
    
#=====================#

#=====================#
#  WMC-No-Gold-Drops  #
#=====================#

# Remove gold drops from mobs

no-gold-drops:
    # Main enable for no gold drops
    enabled: true
    
    # What entities should it remove from
    entities:
        - 'ZOMBIFIED_PIGLIN'
        - 'DROWNED'
    
#=====================#

#=====================#
#      WMC-No-AI      #
#=====================#

# Removes entities ability to target players spawned meeting a criteria

# Follow already layed out pattern
# Gives the ability to tweak mob AI depending on their spawn reasons

no-ai:
    # Main enable for no ai with specific spawn types
    enabled: true
    mobs:
        SKELETON:
            spawn-types:
                - 'SPAWNER'
        BLAZE:
            spawn-types:
                - 'SPAWNER'
        SPIDER:
            spawn-types:
                - 'SPAWNER'
        PIG:
            spawn-types:
                - 'SPAWNER'
        GUARDIAN:
            spawn-types:
                - 'SPAWNER'
        ZOMBIE:
            spawn-types:
                - 'SPAWNER'
        BLAZE:
            spawn-types:
                - 'SPAWNER'
            
#=====================#

#=====================#
#    WMC-Recipes      #
#=====================#

# Recipe modifications

recipes:
    # !Recipes require a server restart to change!
    # Main enable for recipe tweaker
    enabled: true
    
        # List of tweakables (new recipes at bottom):
        # CLOCK, POWERED_RAIL, NETHERITE_INGOT
        # LIGHT_WEIGHTED_PRESSURE_PLATE, 
        # GLISTERING_MELON_SLICE
        #
        # In addition to this you can leave any recipe
        # here which you'd like to disable,
        # if you put for example STICK, it will remove the stick recipe
    tweaked:
        - 'CLOCK'
        - 'POWERED_RAIL'
        
    # dark-prismarine: 8 prismarine with black dye in center makes 8
    add-dark-prismarine: true
    
    # cobweb: 9 string
    add-cobweb: true
    
    #
    # CLOCK: tweaked to 4 yellow dye in corners, iron instead of gold
    # POWERED_RAIL: Iron instead of gold
    # NETHERITE_INGOT: diamond instead of gold
    # LIGHT_WEIGHTED_PRESSURE_PLATE: heavy weighted pressure plate + yellow dye
    # GLISTERING_MELON_SLICE: 8 sugar, 1 melon slice
    #
    
#=====================#

#=====================#
#    WMC-Spawners     #
#=====================#

# Silk spawners

spawners:
    # Main enable for spawners
    enabled: true
    
    # What tools can mine spawners with silk touch?
    allowed-tools:
        - 'DIAMOND_PICKAXE'
        - 'NETHERITE_PICKAXE'
        - 'IRON_PICKAXE'
    
    # Should it delete all non legal spawners
    delete-illegals: true
    
    # Stop illegals from spawning from spawners
    prevent-illegal-spawns: true
    
    # Prevent illegal spawners placement
    prevent-illegal-placement: true
    
    # Should admins be notified about spawners being placed?
    # Permission required: wmc.notifyspawners
    notify-when-placed: false
    
    # Should breaking an illegal spawner be rewarded?
    reward-breaking-illegals: false
    # What does it give in return for deleting it? (raw XP)
    reward-amount: 300
        
    # Do you wish to prevent spawners from exploding?
    cancel-explosion: true
    
    # Should the spawner be placed in the user's inventory automatically
    place-spawner-in-inventory: false
    
    # List of legal mob spawns
    legals:
        - 'PIG'
        - 'SHEEP'
        - 'CHICKEN'
        - 'COW'
        - 'BLAZE'
        - 'ZOMBIE'
        - 'SKELETON'
        - 'SPIDER'
        - 'GUARDIAN'

#=====================#

#=====================#
#    WMC-First-Join   #
#=====================#

# Used to reward players that are nice and welcome players

welcome:
    # Main enable for welcome rewards
    enabled: true
    
    # What commands should it execute, follow the layout below
    reward-commands:
        - 'give {USERNAME} gold_ingot 2'
        
    # How long should they be able to say it for (in seconds)
    reward-time: 10
    
    # What words can be said
    # Will automatically be forced to lower case and symbols will be removed
    message: 'welcome'
    
    # What sound will be played to the player that welcomes
    sound: 'BLOCK_NOTE_BLOCK_PLING'
    pitch: 1.0
    volume: 1.0
    
#=====================#

#=====================#
#      WMC-Combat     #
#=====================#

combat:
    # Main enable for combat tweaking
    enabled: true
    
    # How long are users tagged for when hit
    # by another player
    combat-tag-time: 15 # In seconds
    
    # Should teleporting be disabled
    # when combat tagged
    tag-cancel-tp: true
    
    # Should combat loggers be killed?
    kill-on-combat-log: true
    
    # Should any commands be executed on combat log
    execute-commands: true
    
    # What commands?
    combat-log-commands:
        - 'wmcbroad &2&lWorld&6&lMC &8&l» &c{USERNAME} &fcombat logged and was punished!'        

#=====================#

#=====================#
#    WMC-Protection   #
#=====================#

# enable-protection-for can be the following 
# [ 'FIRST_JOIN', 'RESPAWN' ]
        
protection: 
    # Main enable for player protection
    enabled: true
    
    # How long are users protected for
    protection-time: 1800 # In seconds
    
    # Who should get protected?
    enable-protection-for:
        - 'FIRST_JOIN'
    
    # When should it auto-disable?
    disable-conditions:
        enabled: false
        # Easier aliases: [ SWORD, AXE ], checks any axe/sword
        crafting:
            - 'SWORD'
            - 'AXE'
        pickup:
            - 'SWORD'
            - 'AXE'
    
    # What damage causes should it prevent
    prevented-causes:
        - 'ENTITY_ATTACK'
        - 'ENTITY_SWEEP_ATTACK'
        - 'FIRE'
        - 'FIRE_TICK'
        - 'LAVA'
        - 'PROJECTILE'
        - 'STARVATION'
        
#=====================#
        